import { Raleway, Roboto_Mono, Ubuntu } from "next/font/google";
import "./globals.css";
import "@/app/css/style_site.css";
import "@/app/css/utility.css";

const raleway = Raleway({ subsets: ["latin"] });
const robotoMono = Roboto_Mono({ subsets: ["latin"] });
const ubuntu = Ubuntu({ subsets: ["latin"], weight: "400", style: "italic" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body suppressHydrationWarning={true}  className={ubuntu.className}>
        {children}
      </body>
    </html>
  );
}
